server:
  error.whitelabel.enabled: false
  port: ${SERVER_PORT:8080}

spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        enable_lazy_load_no_trans: true
        temp:
          use_jdbc_metadata_defaults: false
        generate_statistics: true
      javax:
        persistence:
          query.timeout: 10000
  datasource:
    username: ${DB_USERNME}
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useUnicode=true&characterEncoding=utf8&stringtype=unspecified
  banner:
    image:
      location: classpath:banner.png
      width: 100
      height: 15
      margin: 1
logging.config: classpath:logback-${ENV:development}.xml